[package]
name = "ruvy-wasm-sys"
version = "0.1.0"
edition = "2021"

[build-dependencies]
anyhow = { workspace = true }
bindgen = "0.72.0"
cc = "1.2"
ruby-wasm-assets = { path = "../ruby-wasm-assets" }
